# Recall leared stuffs
##### STEP1: Fetch the data set from API 
##### STEP2: And convert it into .CSV file 
##### STEP3: Saved it as data frame 
##### STEP4: Clean and sort data 
##### STEP5: Visualize the data

In [26]:
import pandas as pd
import numpy as np 
import matplotlib.pyplot as plt
import seaborn as sns
# to count hashable item from collection 
from collections import Counter
#used for statistic and find correlation 
from scipy import stats

#Exercise 0
# Fetch data set from API
iris_url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'

# We need colomn names to make dataset easier to index (For example: SLice, dice and move through)
col_name = ["Sepal_length", "Sepal_Width", "Pedal_Length", "Pedal_Width", "Class"] 

#Read the iris dataset into dataframe 
iris = pd.read_csv(iris_url, names=col_name)
#Print fist five values
iris.head()

   Sepal_length  Sepal_Width  Pedal_Length  Pedal_Width        Class
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa

In [27]:
#Print last five data points
iris.tail()

     Sepal_length  Sepal_Width  Pedal_Length  Pedal_Width           Class
145           6.7          3.0           5.2          2.3  Iris-virginica
146           6.3          2.5           5.0          1.9  Iris-virginica
147           6.5          3.0           5.2          2.0  Iris-virginica
148           6.2          3.4           5.4          2.3  Iris-virginica
149           5.9          3.0           5.1          1.8  Iris-virginica

In [28]:
#print the data types of the data
iris.dtypes

Sepal_length    float64
Sepal_Width     float64
Pedal_Length    float64
Pedal_Width     float64
Class            object
dtype: object

In [29]:
# Excercise 1:
# 1.Find all the iris present in dataset 
print(Counter(iris["Class"]))
# 2.Replace each iris class with a numerical value
iris.replace({'Iris-setosa':1, 'Iris-versicolor':2, 'Iris-virginica':3})

Counter({'Iris-setosa': 50, 'Iris-versicolor': 50, 'Iris-virginica': 50})

     Sepal_length  Sepal_Width  Pedal_Length  Pedal_Width  Class
0             5.1          3.5           1.4          0.2      1
1             4.9          3.0           1.4          0.2      1
2             4.7          3.2           1.3          0.2      1
3             4.6          3.1           1.5          0.2      1
4             5.0          3.6           1.4          0.2      1
..            ...          ...           ...          ...    ...
145           6.7          3.0           5.2          2.3      3
146           6.3          2.5           5.0          1.9      3
147           6.5          3.0           5.2          2.0      3
148           6.2          3.4           5.4          2.3      3
149           5.9          3.0           5.1          1.8      3

[150 rows x 5 columns]

![](https://camo.githubusercontent.com/7da1222b4b7619475b570f567fe07eafa1618aecaada63b3a78332cec6c456ec/68747470733a2f2f757365722d696d616765732e67697468756275736572636f6e74656e742e636f6d2f373036353430312f35323037313932372d63316364373130302d323536322d313165392d393038612d6464653931626131346535392e706e67)
#### Filter the values in the table

In [30]:
#Fetch the data of specific class
iris.loc[iris['Class'] == 'Iris-setosa'] # 'loc' method is used to locate some value in a table
# Find the iris member of Iris-setosa that have a sepal_width below 3.5 and pedal_length above 1.4
iris.loc[(iris['Class']=='Iris-setosa') & (iris['Sepal_Width'] < 3.8) & (iris['Pedal_Length'] > 1.4)]

    Sepal_length  Sepal_Width  Pedal_Length  Pedal_Width        Class
3            4.6          3.1           1.5          0.2  Iris-setosa
7            5.0          3.4           1.5          0.2  Iris-setosa
9            4.9          3.1           1.5          0.1  Iris-setosa
10           5.4          3.7           1.5          0.2  Iris-setosa
11           4.8          3.4           1.6          0.2  Iris-setosa
20           5.4          3.4           1.7          0.2  Iris-setosa
21           5.1          3.7           1.5          0.4  Iris-setosa
23           5.1          3.3           1.7          0.5  Iris-setosa
24           4.8          3.4           1.9          0.2  Iris-setosa
25           5.0          3.0           1.6          0.2  Iris-setosa
26           5.0          3.4           1.6          0.4  Iris-setosa
27           5.2          3.5           1.5          0.2  Iris-setosa
29           4.7          3.2           1.6          0.2  Iris-setosa
30           4.8          3.1           1.6          0.2  Iris-setosa
31           5.4          3.4           1.5          0.4  Iris-setosa
34           4.9          3.1           1.5          0.1  Iris-setosa
37           4.9          3.1           1.5          0.1  Iris-setosa
39           5.1          3.4           1.5          0.2  Iris-setosa
43           5.0          3.5           1.6          0.6  Iris-setosa
48           5.3          3.7           1.5          0.2  Iris-setosa

### Pre-Processing and cleaning are done............... so next step is Analytics and visulization

![](https://camo.githubusercontent.com/7da1222b4b7619475b570f567fe07eafa1618aecaada63b3a78332cec6c456ec/68747470733a2f2f757365722d696d616765732e67697468756275736572636f6e74656e742e636f6d2f373036353430312f35323037313932372d63316364373130302d323536322d313165392d393038612d6464653931626131346535392e706e67)
#### Find the correlation

**Exercise 3:** Find the correlation between any two continuous variables in the dataset using [`stats.pearsonr`](https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.pearsonr.html)

In [36]:
stats.pearsonr(iris["Pedal_Length"],iris["Sepal_length"])

PearsonRResult(statistic=0.8717541573048714, pvalue=1.0384540627939325e-47)

![](https://camo.githubusercontent.com/7da1222b4b7619475b570f567fe07eafa1618aecaada63b3a78332cec6c456ec/68747470733a2f2f757365722d696d616765732e67697468756275736572636f6e74656e742e636f6d2f373036353430312f35323037313932372d63316364373130302d323536322d313165392d393038612d6464653931626131346535392e706e67)
#### Exercise 4:Plot the two variables against each other using seaborn linear model plot: [`sns.lmplot`](https://seaborn.pydata.org/generated/seaborn.lmplot.html).

In [37]:
#Plot above data and visualize
sns.lmplot(data = iris, x = "Pedal_Length", y = "Sepal_length" )

NameError: name 'sns' is not defined